spring.application.name=emarket

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.properties.hibernate.dialect=${JPA_HIBERNATE}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.jpa.properties.hibernate.statement_cache.size=0
spring.jpa.properties.hibernate.query.plan_cache_max_size=0
spring.jpa.properties.hibernate.query.plan_parameter_metadata_max_size=0

mail.email=${MAIL_USERNAME}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB